"""
Read ogyropsi.dat ASCII file generated by CHEASE.

This file contains equilibrium data for gyrokinetic codes (GENE & ORB5).
Format: Each variable starts with a name line, followed by data in 5 columns
of 20-character scientific notation (1P5E20.10 format).
"""

import numpy as np


def read_ogyropsi(filename="ogyropsi.dat"):
    """
    Read ogyropsi.dat ASCII file.

    Parameters
    ----------
    filename : str
        Path to the ogyropsi.dat file (default: 'ogyropsi.dat')

    Returns
    -------
    dict
        Dictionary containing all the data from the file with 2D arrays properly reshaped
    """
    data = {}

    with open(filename, "r") as f:
        lines = f.readlines()

    i = 0
    while i < len(lines):
        line = lines[i].strip()

        if not line:
            i += 1
            continue

        # This is a variable name
        var_name = line
        i += 1

        # Read the data
        values = []
        while i < len(lines):
            line = lines[i].strip()
            if not line:
                i += 1
                continue

            # Try to parse as numbers
            try:
                # Split by whitespace and parse as floats
                nums = line.split()
                parsed = [float(x) for x in nums]
                values.extend(parsed)
                i += 1
            except ValueError:
                # This is the next variable name, stop reading data
                break

        # Store the data
        if len(values) == 1:
            data[var_name] = values[0]
        else:
            data[var_name] = np.array(values)

    # Reshape 2D arrays - Fortran is column-major!
    # Get dimensions
    NPSI = int(data["NPSI"])
    NCHI = int(data["NCHI"])
    NRBOX = int(data["NRBOX"])
    NZBOX = int(data["NZBOX"])

    # List of 2D variables on (PSI, CHI) grid
    var2d_psi_chi = [
        "g11",
        "g12",
        "g22",
        "g33",
        "B",
        "dBdpsi",
        "dBdchi",
        "dPsidR",
        "dPsidZ",
        "dChidR",
        "dChidZ",
        "Jacobian",
        "R",
        "Z",
    ]

    # List of 2D variables on (R, Z) grid
    var2d_rz = ["psiRZ", "chiRZ"]

    # Reshape 2D arrays - Fortran is column-major!
    for var in var2d_psi_chi:
        if var in data and isinstance(data[var], np.ndarray):
            if data[var].size == NPSI * NCHI:
                # Fortran writes ((data(i,j),i=1,N1),j=1,N2)
                # which means first index varies fastest
                data[var] = data[var].reshape((NPSI, NCHI), order="F")

    for var in var2d_rz:
        if var in data and isinstance(data[var], np.ndarray):
            if data[var].size == NRBOX * NZBOX:
                data[var] = data[var].reshape((NRBOX, NZBOX), order="F")

    return data
